receivers:
  otlp:
    protocols:
      grpc:
        endpoint: localhost:4317
      http:
        endpoint: localhost:4318

processors:
  batch:
    timeout: 1s
    send_batch_size: 1024
  transform:
    log_statements:
      - context: log
        statements:
          - merge_maps(log.attributes, ParseJSON(log.body), "upsert") where resource.attributes["service.name"] == "grafanacon-otel"
          - set(log.body, log.attributes["msg"]) where resource.attributes["service.name"] == "grafanacon-otel" and log.attributes["msg"] != nil
          - delete_key(log.attributes, "msg") where resource.attributes["service.name"] == "grafanacon-otel" and log.attributes["msg"] != nil

exporters:
  otlphttp/logs:
    endpoint: ${OTLP_ENDPOINT}
    tls:
      insecure: true

service:
  pipelines:
    logs:
      receivers: [otlp]
      processors: [batch, transform]
      exporters: [otlphttp/logs]
